version: '3'
services:
  db:
    image: mysql:5.7.33
    volumes:
      - <add directory> :/var/lib/mysql
    environment:
      MYSQL_DATABASE: <add name>
      MYSQL_ROOT_PASSWORD: <add password for root>
      MYSQL_USER: <add user>
      MYSQL_PASSWORD: <add password>
    networks:
      - net
    restart: always

  web:
    depends_on:
      - db
    image: wordpress:5.7.0-apache
    volumes:
      - <add directory>:/var/lib/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: <add name>
      WORDPRESS_DB_USER: <add user>
      WORDPRESS_DB_PASSWORD: <add password>
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "false"
      WP_DEBUG_LOG: "true"
    ports:
     - "8080:80"
    networks:
     - net
    restart: always

networks:
  net:
