version: '3'
services:
  db:
    image: mysql:5.7.33
    volumes:
      - /Users/smaelmouheb/Docker/app :/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_sma
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sma
      MYSQL_PASSWORD: sma
    networks:
      - net
    restart: always

  web:
    depends_on:
      - db
    image: wordpress:5.7.0-apache
    volumes:
      - /Users/smaelmouheb/Docker/wp :/var/lib/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: db_sma
      WORDPRESS_DB_USER: sma
      WORDPRESS_DB_PASSWORD: sma
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "false"
      WP_DEBUG_LOG: "true"
    ports:
     - "8080:80"
    networks:
     - net
    restart: always

networks:
  net:
