version: '3'
services:
  db:
    image: mysql:5.7.33
    volumes:
      - <path to your host folder> :/var/lib/mysql
    environment:
      MYSQL_DATABASE: <add your db name>
      MYSQL_ROOT_PASSWORD: <add a password for root>
      MYSQL_USER: <add username>
      MYSQL_PASSWORD: <add password>
    ports:
      - "3306:3306"
    networks:
      - net
    restart: always

  web:
    depends_on:
      - db
    image: wordpress:5.7.0-apache
    volumes:
      - <path to your host folder> :/var/lib/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: <add data from db above>
      WORDPRESS_DB_USER: <add data from db above>
      WORDPRESS_DB_PASSWORD: <add data from db above>
    ports:
     - "8080:80"
    networks:
     - net
    restart: always

networks:
  net:
